### ISSUE TITLE
I/O operation on closed file and list index out of range errors

### ISSUE THREAD

**Issue by matthewbenstead** [pacificclimate/pdp_util#14] opened 2020-02-26 17:45 UTC
The following errors were seen in the PDP backend container running in the cloud: 
```
2020-02-26 08:15:56 [11] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 114, in handle_request
    for item in respiter:
  File "/root/pdp/pdp/error.py", line 74, in __call__
    start_response(status, response_headers, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 237, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/root/pdp/pdp/error.py", line 68, in __call__
    for block in response_iter:
  File "/usr/local/lib/python2.7/dist-packages/ga_wsgi_client/__init__.py", line 41, in __call__
    for chunk in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/pdp_util/agg.py", line 76, in ziperator
    for name, responder in responders:
  File "/usr/local/lib/python2.7/dist-packages/pdp_util/agg.py", line 94, in get_all_metadata_index_responders
    nets = set(zip(*stations)[0])
IndexError: list index out of range
Exception ValueError: 'I/O operation on closed file' in <bound method ZipFile.__del__ of <zipfile.ZipFile object at 0x7f184a5bc190>> ignored
2020-02-26 08:15:57 [11] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 114, in handle_request
    for item in respiter:
  File "/root/pdp/pdp/error.py", line 74, in __call__
    start_response(status, response_headers, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 237, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/root/pdp/pdp/error.py", line 68, in __call__
    for block in response_iter:
  File "/usr/local/lib/python2.7/dist-packages/ga_wsgi_client/__init__.py", line 41, in __call__
    for chunk in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/pdp_util/agg.py", line 76, in ziperator
    for name, responder in responders:
  File "/usr/local/lib/python2.7/dist-packages/pdp_util/agg.py", line 94, in get_all_metadata_index_responders
    nets = set(zip(*stations)[0])
IndexError: list index out of range
2020-02-26 08:15:57 [11] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 114, in handle_request
    for item in respiter:
  File "/root/pdp/pdp/error.py", line 74, in __call__
    start_response(status, response_headers, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 237, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/root/pdp/pdp/error.py", line 68, in __call__
    for block in response_iter:
  File "/usr/local/lib/python2.7/dist-packages/ga_wsgi_client/__init__.py", line 41, in __call__
    for chunk in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/pdp_util/agg.py", line 76, in ziperator
    for name, responder in responders:
  File "/usr/local/lib/python2.7/dist-packages/pdp_util/agg.py", line 94, in get_all_metadata_index_responders
    nets = set(zip(*stations)[0])
IndexError: list index out of range
Exception ValueError: 'I/O operation on closed file' in <bound method ZipFile.__del__ of <zipfile.ZipFile object at 0x7f1849c7ba90>> ignored
```

Based on the thread ID's I believe it was this request which corresponds to these errors: 
```
2020-02-26 05:21:26 [11] [INFO] <IP ADDR REMOVED> - - [26/Feb/2020:05:21:26 +0000] "GET /downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_MIROC5_historical+rcp26_r1i1p1_19500101-21001231.nc.nc?tasmin[0:55151][134:137][172:176]& HTTP/1.1" 200 26
49476 "-" "R (3.5.3 x86_64-w64-mingw32 x86_64 mingw32)"
```

**Comment by jameshiebert** [comment] 2020-02-26 17:51
> Based on the thread ID's I believe it was this request which corresponds to these errors:

`pdp_util` and `agg.py` are only used for the PCDS portal, so I don't think that's possible. Were there any `/pcds` endpoint requests around this time?

**Comment by matthewbenstead** [comment] 2020-02-26 17:53
Yeah - the request took place quite a bit before the errors so I wasn't sure, but was just searching backwards based on the thread ID.

**Comment by jameshiebert** [comment] 2021-01-14 17:48
Duplicate of #8

**Closed by jameshiebert** 2021-01-14 17:48 UTC
